### ISSUE TITLE
Enable link functionality for dimensions

### ISSUE THREAD

**Issue by jakeyoos** [looker/viz-collapsible_tree-marketplace#1]
Collapsible Tree seems to be the best way to visualize hierarchies, so it would be natural to show something like an org chart using the tree.  But if I have a `link` parameter defined on a dimension in LookML, it does not come through into the visualization.  This keeps me from, say, linking from the vis to a "Employee" lookup dashboard or a "manager" lookup dashboard or whatever.

**Comment by thomasbanghart** [comment]
@jakeyoos we just added support for simple link parameters -- you should be able to update the viz via the marketplace to get them going. I say "simple" links because liquid references other than `{{value}}` may not work as expected. For example,  {{<other_view>.<field>._value}} could cause a fanout in the data table that wouldn't carry over to the viz. 

Let us know if that does the trick for your purposes - thanks!
